name: caller
on:
  workflow_dispatch:

jobs:
  call-build:
    uses: sreeharinath1/read/.github/workflows/reusable_build.yaml@main
    with:
      java-version: '21'
      environment: staging
      
    
