name: concurrency example
on:
  workflow_dispatch:
concurrency:
  group: deploy-production
  cancel-in-progress: false
jobs:
  build:
    runs-on: ubuntu-latest
    concurrency:
    group: deploy-production
  cancel-in-progress: false
    steps:
      - name: Checkout Code
        uses: actions/checkout@v4
      - name: deploy
        run: |
          echo "Deployment in Production"
