name: container

on:
  workflow_dispatch:
jobs:
  test:
    runs-on: ubuntu-latest
    container:
      image: mavan:3.9.6-eclipse-temurin-17
      env:
        MAVEN_OPTS: "-Xmx512m"
    steps:
      - uses: actions/checkout@v4
      - name: Check maven version
        run: mvn --version
      - name: Check Java version
        run: java --version
     
