name: java setup

on:
  workflow_dispatch: 
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
jobs:
  java-setup:
    runs-on: ubuntu-latest
    steps:
      - name: Install Java
        uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: '17'
      - name: Checking Java-version
        run: java --version
  multiple-java:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        java-version: [11, 17, 21]
    steps:
      - name: Install Java -versions
        uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: ${{ matrix.java-version }}
      - name: Checking Installed Jversions
        run: java --version
        
