name: Matric Strategy
on:
  workflow_dispatch:
jobs:
  matrix_test:
    strategy:
      matrix:
        os: [ ubuntu-latest,windows-lates,macos-latest ]
        node-version: [ 16, 18, 20 ]
    runs-on: ${{matrix.os}}
    steps:
      - name: code checkout
        uses: actions/checkout@v4
      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: ${{ matrix.node-versions }}
      - name: Tessting correct installation
        run: npm -v
