name: secrets access

on:
  workflow_dispatch:
jobs:
  secret_access:
    runs-on: ubuntu-latest
    steps:
      - name: checking access
        env:
          DB: ${{ secrets.DB }}
          DB_USER: ${{ secrets.DB_USER }}
          DB_PASS: ${{ secrets.DB_PASS }}
        run: echo " $DB, $DB_USER, $DB_PASS"
